### ISSUE TITLE
Allow to translate texts in English in live search

### ISSUE THREAD

**Issue by agaraban** [AdobeDocs/commerce-merchant-services.es-ES#1]
Right now we are trying to translate "View All" and "Suggestions" in autocomplete, but we realized that this sec element is created by jaavscript and comes from an external magento service. We want to know if they are going to release a fix to solve this issue for multilanguage pages.

**Comment by yanlicao** [comment]
Thanks for your feedback, could you kindly give us a bit more details on how to reproduce this issue? we will submit this as improvement requests accordingly.

**Comment by yanlicao** [comment]
Hi @agaraban , thanks for your feedback, could you kindly give us a bit more details on how to reproduce this issue? we will submit this as improvement requests accordingly.  This is being reviewed and tracked in https://jira.corp.adobe.com/browse/G11N-10258.

**Comment by yanlicao** [comment]
Dear @agaraban , just want to follow up this, could you kindly share with us a bit more details?
for example where we can see those strings , any example?  More info will be helpful for us to do trouble shooting. 
Thanks for your help!

**Comment by yanlicao** [comment]
Dear @agaraban , just want to check if you can kindly share with us more info about this issue?

**Comment by yanlicao** [comment]
Dear @agaraban , we have not received a response and so will close this ticket. If you continue to experience the issue, please open a new ticket.
